# Generated by Django 4.2.5 on 2023-10-03 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0004_portfolio_project_student_portfolio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='portfolio',
        ),
    ]
