# Generated by Django 4.2.5 on 2023-11-05 03:35

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0010_delete_projectsinportfolio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('platform', models.CharField(choices=[('YT', 'Youtube'), ('TTV', 'Twitch'), ('TT', 'Tiktok'), ('IG', 'Instagram'), ('X', 'Twitter'), ('Other', 'Other')], max_length=200)),
            ],
            managers=[
                ('videos', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveField(
            model_name='project',
            name='portfolio',
        ),
        migrations.RemoveField(
            model_name='student',
            name='portfolio',
        ),
        migrations.DeleteModel(
            name='Portfolio',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
