# Generated by Django 4.2.5 on 2023-10-03 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0002_portfolio_project_alter_student_major_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.RemoveField(
            model_name='student',
            name='portfolio',
        ),
        migrations.DeleteModel(
            name='Portfolio',
        ),
    ]
