# Generated by Django 4.2.5 on 2023-10-12 15:57

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0008_projectsinportfolio'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='portfolio',
            managers=[
                ('portfolios', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='project',
            managers=[
                ('projects', django.db.models.manager.Manager()),
            ],
        ),
    ]
